/**************************************************************************

 The SCND Genesis: Legends is a fighting game based on THE SCND GENESIS,
 a webcomic created by Ifunga Ndana (https://www.scndgen.com).

 The SCND Genesis: Legends RMX  © 2017 Ifunga Ndana.

 The SCND Genesis: Legends is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
    10| the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 The SCND Genesis: Legends is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with The SCND Genesis: Legends. If not, see <https://www.gnu.org/licenses/>.

 **************************************************************************/
package com.scndgen.legends;

/**
 * Named indexes into {@code translations/*.json} for menus, HUD, and system copy.
 * Story dialogue lives on {@link StoryKey}.
 */
public enum LangKey implements TextKey {
    OFF(1),
    QUALITY_HIGH(2),
    QUALITY_MEDIUM(3),
    QUALITY_LOW(4),
    DIFFICULTY_SETTING(6),
    DIALOGUE_SPEED(7),
    TIME_DURATION(14),
    COMIC_OCCURRENCE(17),
    SELECTED_LANGUAGE(19),
    SAVE(20),
    SPEED_INSANE(22),
    SPEED_FAST(23),
    SPEED_NORMAL(24),
    SPEED_SLOW(25),
    ARE_YOU_INSANE(26),
    HARD(27),
    MEDIUM(28),
    EASY(29),
    YOU_SUCK(30),
    RESET(31),
    GAME_OPTIONS(34),
    OK(36),
    KEYBOARD(37),
    SELECT(38),
    CANCEL_SELECTION(39),
    ENTER(40),
    BACKSPACE(41),
    SCREENSHOT(42),
    PAUSE_RESUME(43),
    TRIGGER_FURY(44),
    LEFT_PREVIOUS(45),
    RIGHT_NEXT(46),
    UP(47),
    DOWN(48),
    FIGURE_THIS_OUT(49),
    EXIT_GAME(50),
    ACH_UPPER_HAND(61),
    ACH_BEAT_THE_ODDS(62),
    ACH_OWNAGE(63),
    ACH_HEARTLESS(64),
    ACH_MEANIE(65),
    ACH_RAGE(66),
    ACH_WINNER(67),
    ACH_BUZZ_KILL(68),
    ACH_CLOSE_CALL(69),
    ACH_ON_A_ROLL(70),
    ACH_HALF_WAY(71),
    ACH_UPPER_HAND_DESC(72),
    ACH_BEAT_THE_ODDS_DESC(73),
    ACH_OWNAGE_DESC(74),
    ACH_HEARTLESS_DESC(75),
    ACH_MEANIE_DESC(76),
    ACH_RAGE_DESC(77),
    ACH_WINNER_DESC(78),
    ACH_BUZZ_KILL_DESC(79),
    ACH_CLOSE_CALL_DESC(80),
    ACH_ON_A_ROLL_DESC(81),
    ACH_HALF_WAY_DESC(82),
    LEAVE_CONFIRM(110),
    QUIT_SERIOUSLY_BODY(111),
    STORY_COMPLETE(115),
    STAT_NAME(118),
    STAT_POINTS(119),
    STAT_PLAY_TIME(120),
    STAT_ACH_UNLOCKED(121),
    STAT_ACH_TRIGGERED(122),
    STAT_MATCH_COUNT(123),
    STAT_AVG_POINTS(124),
    STAT_WINS(125),
    STAT_LOSSES(126),
    STAT_STYLE(127),
    STAT_FAVORITE(128),
    STAT_STORY_PROGRESS(129),
    STAT_COMPLETION(130),
    PRESS_ENTER_EXIT(131),
    COMPLETE(132),
    ACTIVATED(133),
    DESC_RAILA(134),
    DESC_SUBIYA(135),
    DESC_LYNX(136),
    DESC_AISHA(137),
    DESC_RAVAGE(138),
    DESC_ADE(139),
    DESC_JONAH(140),
    DESC_ADAM(141),
    DESC_NOVA_ADAM(142),
    DESC_AZARIA(143),
    DESC_SORROWE(144),
    DESC_THING(145),
    PRESS_ENTER_PROCEED(146),
    BACKSPACE_CANCEL_SELECTIONS(147),
    PAUSED(148),
    F5_CANCEL_MATCH(149),
    ESC_RESUME(150),
    STAGE_IBEX_HILL(152),
    STAGE_CHESTON_DOCKS(153),
    STAGE_RUINED_HALL(154),
    STAGE_CHESTON_STREETS(155),
    STAGE_IBEX_NIGHT(156),
    STAGE_SCORCHED(157),
    STAGE_FROZEN(158),
    STAGE_HIDDEN_CAVE(159),
    STAGE_AFRICAN_VILLAGE(160),
    STAGE_APOCALYPSE(161),
    STAGE_DISTANT_ISLE(162),
    STAGE_MOONLIT_SHORE(163),
    STAGE_RANDOM(164),
    LOADING(165),
    WAITING_STAGE(166),
    MACHINE_NAME(167),
    PARTNER_HINT(168),
    MACHINE_IP_HINT(169),
    YES(171),
    NO(172),
    STORY_MODE(307),
    QUICK_MATCH(308),
    HOST_LAN(309),
    JOIN_LAN(310),
    YOUR_STATS(311),
    OPTIONS(312),
    VIEW_CONTROLS(313),
    ABOUT(314),
    EXIT(315),
    ACHIEVEMENT_LOCKER(316),
    TUTORIAL(319),
    PRESS_ENTER_SKIP(343),
    TUTORIAL_CM(355),
    TUTORIAL_INTRO(356),
    TUTORIAL_AB(357),
    TUTORIAL_FB(358),
    TUTORIAL_ATTACKS(359),
    TUTORIAL_HUD(360),
    SLIDE(365),
    KEYBOARD_SHORTCUTS(366),
    PRESS_ESC_BACK(368),
    STAGE_RUINED_HALL_NIGHT(369),
    STAGE_SCORCHED_NIGHT(370),
    STAGE_HIDDEN_CAVE_NIGHT(371),
    SOUND_VOLUME(418),
    MUSIC_VOLUME(419),
    VOICE_VOLUME(420),
    CANCEL(421),
    EXIT_TITLE(422),
    SERIOUSLY(423),
    INFINITE(424),
    CONNECT_TO_HOST(450),
    ENTER_HOST(451),
    MACHINE_IP(452),
    COPYRIGHT_RMX(453),
    PRESS_FEEDBACK(456),
    PRESS_BLOG(457),
    PRESS_FACEBOOK(458),
    HP(459),
    WAITING_HOST(460),
    SCENE(461),
    CONFIRMATION(462),
    DUDE(463),
    QUIT_MATCH(464),
    ARE_YOU_SURE(465),
    TERMINATE_SESSION(466),
    NUKE_FROM_ORBIT(467),
    HEADS_UP(468),
    SOMEONE_WANTS_FIGHT(469),
    WASTE_EM(470),
    YIKES(471),
    CANCEL_NETWORK_SESSION(472),
    NO_GOING_BACK(473),
    SWEETNESS(474),
    OUCHIES(475),
    HARSH(476),
    OPPONENT_REFUSED(477),
    SESSION_TERMINATED(478),
    THAT_SUCKS(479),
    NETWORK_ERROR(480),
    SESSION_WENT_WRONG(481),
    RESOLUTION(482),
    REFRESH_NOTE(483),
    LETTERBOX_NOTE(484),
    LETTERBOX_COLOR(485),
    LICENSE(486),
    CHANGELOG(487),
    SOURCE(488),
    BUILD(489),
    KEY_DOWN_ENTER(491),
    KEY_F12(492),
    KEY_ESC(493),
    KEY_L(494),
    KEY_LEFT(495),
    KEY_RIGHT(496),
    KEY_UP(497),
    TIMES(498),
    HIDDEN_ACHIEVEMENT(499),
    PLAY_TIME_MINUTES(504),
    PLAY_TIME_HOURS(506),
    PLAY_TIME_DAYS(509);

    private final int id;

    LangKey(int id) {
        this.id = id;
    }

    @Override
    public int id() {
        return id;
    }
}
